backend:
  name: test-repo #git-gateway
  branch: master

media_folder: static/images/uploads
public_folder: /images/uploads

collections:
  - name: "products"
    label: "Post"
    folder: "content"
    create: true
    slug: "{{slug}}"
    media_folder: ""
    public_folder: ""
    path: "{{slug}}/index"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - {
          label: "Short description",
          name: "short_description",
          widget: "string",
        }
      - { label: "Full description", name: "full_disc", widget: "string" }
      - label: "All Imgs"
        name: "all_imgs"
        widget: "list"
        fields:
          - {
              name: "imgUrl",
              label: "Img Url",
              widget: "string",
              default: "https://firebasestorage.googleapis.com/v0/b/theater-53375.appspot.com/o/eventsImgs%2Fnatali%2FScreenshot%20from%202024-05-07%2013-58-44.png?alt=media&token=4423fd48-dd3a-4a6c-9cd8-0482ef847a6f",
            }
          - {
              name: "postUrl",
              label: "Post Url",
              widget: "string",
              default: "https://www.instagram.com/p/CkTlZBgp20i/?img_index=2",
            }
