backend:
  name: git-gateway #git-gateway
  branch: main

media_folder: static/images/
public_folder: /images/

collections:
  - name: "products"
    label: "projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Short description", name: "description", widget: "string" }
      - {
          label: "Full description",
          name: "full_description",
          widget: "string",
        }
      - {
          label: "Preview img",
          name: "preview_img",
          widget: "image",
          public_folder: ./,
        }
      - {
          label: "Preview video",
          name: "preview_video",
          widget: "file",
          public_folder: ./,
        }
      - {
          label: "Complete Date",
          name: "complete_date",
          widget: "datetime",
          format: "YYYY-MM-DD",
        }
      - label: "All Imgs"
        name: "all_imgs"
        widget: "list"
        fields:
          - {
              name: "imgUrl",
              label: "Img Url",
              widget: "image",
              public_folder: ./,
            }
          - { name: "postUrl", label: "Post Url", widget: "string" }
      - label: "Customer review"
        name: "customerReview"
        widget: "object"
        fields:
          - { name: "link", label: "Link on customer", widget: "string" }
          - {
              name: "customerImg",
              label: "Customer img",
              widget: "image",
              public_folder: ./,
            }
          - {
              name: "customerFeedBack",
              label: "Customer feedback",
              widget: "string",
            }
          - { name: "customerName", label: "Customer name", widget: "string" }
